version: '3.8'

services:
  app:
    restart: unless-stopped
    build:
      context: .
      target: dev #
    container_name: coursenexus_app_dev
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: coursenexus_db
    environment:
      - POSTGRES_DB=coursenexus
      - POSTGRES_USER=coursenexus
      - POSTGRES_PASSWORD=coursenexus
    volumes:
      - ./database_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pay-bot:
    build:
      context: .
      target: production
    container_name: pay_telegram_bot
    command: npx tsx server/pay-telegram-bot.ts
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    restart: unless-stopped
