import { db } from "./db";
import { tasks } from "@shared/schema";

export async function seedTasks() {
  const existingTasks = await db.select().from(tasks).limit(1);
  
  if (existingTasks.length > 0) {
    console.log("Tasks already seeded, skipping...");
    return;
  }

  console.log("Seeding tasks...");
  
  await db.insert(tasks).values([
    // ONBOARDING TASKS (Level 1) - Easy, Sequential
    {
      title: "Добро пожаловать!",
      description: "Зарегистрируйтесь на платформе и начните свой путь к знаниям",
      reward: 50,
      type: "onboarding",
      category: "general",
      difficulty: "easy",
      requiredLevel: 1,
      targetValue: 1,
      icon: "user-plus",
      displayOrder: 1,
    },
    {
      title: "Первые шаги",
      description: "Заполните профиль: добавьте номер телефона и телеграм ник",
      reward: 25,
      type: "onboarding",
      category: "general",
      difficulty: "easy",
      requiredLevel: 1,
      targetValue: 1,
      icon: "user",
      displayOrder: 2,
    },
    {
      title: "Исследователь",
      description: "Просмотрите 5 различных курсов в магазине",
      reward: 30,
      type: "onboarding",
      category: "courses",
      difficulty: "easy",
      requiredLevel: 1,
      targetValue: 5,
      icon: "search",
      displayOrder: 3,
    },

    // DAILY TASKS (Repeatable) - Easy
    {
      title: "Ежедневный вход",
      description: "Заходите на платформу каждый день и получайте фантики",
      reward: 10,
      type: "daily",
      category: "engagement",
      difficulty: "easy",
      requiredLevel: 1,
      targetValue: 1,
      icon: "calendar-check",
      displayOrder: 10,
      isRepeatable: true,
      resetPeriod: "daily",
    },
    {
      title: "Активный день",
      description: "Просмотрите 3 урока за сегодня",
      reward: 20,
      type: "daily",
      category: "engagement",
      difficulty: "easy",
      requiredLevel: 1,
      targetValue: 3,
      icon: "play-circle",
      displayOrder: 11,
      isRepeatable: true,
      resetPeriod: "daily",
    },
    {
      title: "Коллекционер дня",
      description: "Добавьте 2 курса в избранное сегодня",
      reward: 15,
      type: "daily",
      category: "courses",
      difficulty: "easy",
      requiredLevel: 1,
      targetValue: 2,
      icon: "heart",
      displayOrder: 12,
      isRepeatable: true,
      resetPeriod: "daily",
    },

    // WEEKLY TASKS (Repeatable) - Medium
    {
      title: "Неделя обучения",
      description: "Просмотрите 15 уроков за неделю",
      reward: 80,
      type: "weekly",
      category: "engagement",
      difficulty: "medium",
      requiredLevel: 2,
      targetValue: 15,
      icon: "trending-up",
      displayOrder: 20,
      isRepeatable: true,
      resetPeriod: "weekly",
    },
    {
      title: "Активный ученик",
      description: "Заходите на платформу 5 дней в течение недели",
      reward: 60,
      type: "weekly",
      category: "engagement",
      difficulty: "medium",
      requiredLevel: 2,
      targetValue: 5,
      icon: "zap",
      displayOrder: 21,
      isRepeatable: true,
      resetPeriod: "weekly",
    },

    // COURSE PURCHASE ACHIEVEMENTS - Progressive
    {
      title: "Первый курс",
      description: "Купите ваш первый курс и начните обучение",
      reward: 100,
      type: "achievement",
      category: "courses",
      difficulty: "easy",
      requiredLevel: 1,
      targetValue: 1,
      icon: "shopping-bag",
      displayOrder: 30,
    },
    {
      title: "Коллекция растет",
      description: "Купите 3 курса",
      reward: 150,
      type: "achievement",
      category: "courses",
      difficulty: "medium",
      requiredLevel: 1,
      targetValue: 3,
      icon: "shopping-cart",
      displayOrder: 31,
    },
    {
      title: "Библиотека знаний",
      description: "Купите 5 курсов и расширьте свои знания",
      reward: 250,
      type: "achievement",
      category: "courses",
      difficulty: "medium",
      requiredLevel: 2,
      targetValue: 5,
      icon: "book-open",
      displayOrder: 32,
    },
    {
      title: "Знаток",
      description: "Купите 10 курсов",
      reward: 400,
      type: "achievement",
      category: "courses",
      difficulty: "hard",
      requiredLevel: 3,
      targetValue: 10,
      icon: "award",
      displayOrder: 33,
    },
    {
      title: "Мастер обучения",
      description: "Купите 20 курсов",
      reward: 700,
      type: "achievement",
      category: "courses",
      difficulty: "expert",
      requiredLevel: 5,
      targetValue: 20,
      icon: "crown",
      displayOrder: 34,
    },
    {
      title: "Легенда платформы",
      description: "Купите 50 курсов",
      reward: 2000,
      type: "achievement",
      category: "courses",
      difficulty: "expert",
      requiredLevel: 10,
      targetValue: 50,
      icon: "gem",
      displayOrder: 35,
    },

    // SOCIAL ACHIEVEMENTS - Referral based
    {
      title: "Подписка на Telegram",
      description: "Подпишитесь на наш Telegram-канал и будьте в курсе всех новостей",
      reward: 50,
      type: "achievement",
      category: "social",
      difficulty: "easy",
      requiredLevel: 1,
      targetValue: 1,
      icon: "message-circle",
      displayOrder: 38,
    },
    {
      title: "Делись знаниями",
      description: "Пригласите своего первого друга",
      reward: 75,
      type: "achievement",
      category: "social",
      difficulty: "easy",
      requiredLevel: 1,
      targetValue: 1,
      icon: "users",
      displayOrder: 40,
    },
    {
      title: "Лидер мнений",
      description: "Пригласите 5 друзей на платформу",
      reward: 250,
      type: "achievement",
      category: "social",
      difficulty: "medium",
      requiredLevel: 2,
      targetValue: 5,
      icon: "megaphone",
      displayOrder: 41,
    },
    {
      title: "Амбассадор",
      description: "Пригласите 10 друзей",
      reward: 500,
      type: "achievement",
      category: "social",
      difficulty: "hard",
      requiredLevel: 3,
      targetValue: 10,
      icon: "star",
      displayOrder: 42,
    },
    {
      title: "Суперзвезда",
      description: "Пригласите 25 друзей",
      reward: 1200,
      type: "achievement",
      category: "social",
      difficulty: "expert",
      requiredLevel: 5,
      targetValue: 25,
      icon: "sparkles",
      displayOrder: 43,
    },

    // REVIEW ACHIEVEMENTS
    {
      title: "Первый отзыв",
      description: "Оставьте свой первый отзыв о курсе",
      reward: 50,
      type: "achievement",
      category: "engagement",
      difficulty: "easy",
      requiredLevel: 1,
      targetValue: 1,
      icon: "message-circle",
      displayOrder: 50,
    },
    {
      title: "Критик",
      description: "Оставьте 5 отзывов о пройденных курсах",
      reward: 150,
      type: "achievement",
      category: "engagement",
      difficulty: "medium",
      requiredLevel: 2,
      targetValue: 5,
      icon: "edit",
      displayOrder: 51,
    },
    {
      title: "Экспертное мнение",
      description: "Оставьте 10 подробных отзывов",
      reward: 300,
      type: "achievement",
      category: "engagement",
      difficulty: "hard",
      requiredLevel: 3,
      targetValue: 10,
      icon: "feather",
      displayOrder: 52,
    },

    // FAVORITES ACHIEVEMENTS
    {
      title: "Избранное",
      description: "Добавьте 5 курсов в список избранного",
      reward: 50,
      type: "achievement",
      category: "courses",
      difficulty: "easy",
      requiredLevel: 1,
      targetValue: 5,
      icon: "heart",
      displayOrder: 60,
    },
    {
      title: "Коллекционер желаний",
      description: "Добавьте 15 курсов в избранное",
      reward: 120,
      type: "achievement",
      category: "courses",
      difficulty: "medium",
      requiredLevel: 2,
      targetValue: 15,
      icon: "bookmark",
      displayOrder: 61,
    },
    {
      title: "Мечтатель",
      description: "Добавьте 30 курсов в избранное",
      reward: 250,
      type: "achievement",
      category: "courses",
      difficulty: "hard",
      requiredLevel: 3,
      targetValue: 30,
      icon: "star",
      displayOrder: 62,
    },

    // LESSON VIEWING ACHIEVEMENTS
    {
      title: "Первый урок",
      description: "Просмотрите ваш первый видео-урок",
      reward: 25,
      type: "achievement",
      category: "engagement",
      difficulty: "easy",
      requiredLevel: 1,
      targetValue: 1,
      icon: "play",
      displayOrder: 70,
    },
    {
      title: "Начинающий студент",
      description: "Просмотрите 10 уроков",
      reward: 75,
      type: "achievement",
      category: "engagement",
      difficulty: "easy",
      requiredLevel: 1,
      targetValue: 10,
      icon: "video",
      displayOrder: 71,
    },
    {
      title: "Активный студент",
      description: "Просмотрите 50 уроков",
      reward: 200,
      type: "achievement",
      category: "engagement",
      difficulty: "medium",
      requiredLevel: 2,
      targetValue: 50,
      icon: "tv",
      displayOrder: 72,
    },
    {
      title: "Продвинутый студент",
      description: "Просмотрите 100 уроков",
      reward: 400,
      type: "achievement",
      category: "engagement",
      difficulty: "hard",
      requiredLevel: 3,
      targetValue: 100,
      icon: "film",
      displayOrder: 73,
    },
    {
      title: "Гуру обучения",
      description: "Просмотрите 250 уроков",
      reward: 750,
      type: "achievement",
      category: "engagement",
      difficulty: "expert",
      requiredLevel: 5,
      targetValue: 250,
      icon: "graduation-cap",
      displayOrder: 74,
    },

    // MILESTONE ACHIEVEMENTS
    {
      title: "Первая неделя",
      description: "Проведите 7 дней на платформе",
      reward: 75,
      type: "achievement",
      category: "milestones",
      difficulty: "easy",
      requiredLevel: 1,
      targetValue: 7,
      icon: "calendar",
      displayOrder: 90,
    },
    {
      title: "Месяц с нами",
      description: "Проведите 30 дней на платформе",
      reward: 250,
      type: "achievement",
      category: "milestones",
      difficulty: "medium",
      requiredLevel: 2,
      targetValue: 30,
      icon: "clock",
      displayOrder: 91,
    },
    {
      title: "Квартал обучения",
      description: "Проведите 90 дней на платформе",
      reward: 500,
      type: "achievement",
      category: "milestones",
      difficulty: "hard",
      requiredLevel: 3,
      targetValue: 90,
      icon: "trending-up",
      displayOrder: 92,
    },
    {
      title: "Год с нами!",
      description: "Проведите 365 дней на нашей платформе обучения",
      reward: 1500,
      type: "achievement",
      category: "milestones",
      difficulty: "expert",
      requiredLevel: 5,
      targetValue: 365,
      icon: "party-popper",
      displayOrder: 93,
    },

    // SPENDING MILESTONES
    {
      title: "Первая покупка",
      description: "Потратьте 1000 рублей на обучающие курсы",
      reward: 50,
      type: "achievement",
      category: "milestones",
      difficulty: "easy",
      requiredLevel: 1,
      targetValue: 1000,
      icon: "credit-card",
      displayOrder: 100,
    },
    {
      title: "Инвестор в знания",
      description: "Потратьте 5000 рублей на курсы",
      reward: 150,
      type: "achievement",
      category: "milestones",
      difficulty: "medium",
      requiredLevel: 2,
      targetValue: 5000,
      icon: "trending-up",
      displayOrder: 101,
    },
    {
      title: "Серьёзный инвестор",
      description: "Потратьте 10000 рублей на обучение",
      reward: 400,
      type: "achievement",
      category: "milestones",
      difficulty: "hard",
      requiredLevel: 3,
      targetValue: 10000,
      icon: "briefcase",
      displayOrder: 102,
    },
    {
      title: "VIP клиент",
      description: "Потратьте 25000 рублей на курсы",
      reward: 1000,
      type: "achievement",
      category: "milestones",
      difficulty: "expert",
      requiredLevel: 5,
      targetValue: 25000,
      icon: "gem",
      displayOrder: 103,
    },

    // COMPLETION ACHIEVEMENTS
    {
      title: "Первое завершение",
      description: "Завершите любой курс на 100%",
      reward: 150,
      type: "achievement",
      category: "engagement",
      difficulty: "medium",
      requiredLevel: 1,
      targetValue: 1,
      icon: "check-circle",
      displayOrder: 110,
    },
    {
      title: "Целеустремлённый",
      description: "Завершите 3 курса на 100%",
      reward: 300,
      type: "achievement",
      category: "engagement",
      difficulty: "medium",
      requiredLevel: 2,
      targetValue: 3,
      icon: "target",
      displayOrder: 111,
    },
    {
      title: "Перфекционист",
      description: "Завершите 5 курсов на 100%",
      reward: 500,
      type: "achievement",
      category: "engagement",
      difficulty: "hard",
      requiredLevel: 3,
      targetValue: 5,
      icon: "award",
      displayOrder: 112,
    },
    {
      title: "Мастер завершений",
      description: "Завершите 10 курсов полностью",
      reward: 1000,
      type: "achievement",
      category: "engagement",
      difficulty: "expert",
      requiredLevel: 5,
      targetValue: 10,
      icon: "trophy",
      displayOrder: 113,
    },

    // ENGAGEMENT ACHIEVEMENTS
    {
      title: "Регулярность - залог успеха",
      description: "Заходите на платформу 30 дней подряд без пропусков",
      reward: 400,
      type: "achievement",
      category: "engagement",
      difficulty: "hard",
      requiredLevel: 3,
      targetValue: 30,
      icon: "flame",
      displayOrder: 120,
    },
    {
      title: "Железная воля",
      description: "Заходите на платформу 100 дней подряд",
      reward: 1200,
      type: "achievement",
      category: "engagement",
      difficulty: "expert",
      requiredLevel: 5,
      targetValue: 100,
      icon: "zap",
      displayOrder: 121,
    },

    // SPECIAL ACHIEVEMENTS
    {
      title: "Ночной совёнок",
      description: "Просмотрите урок между полуночью и 6 утра",
      reward: 50,
      type: "achievement",
      category: "engagement",
      difficulty: "easy",
      requiredLevel: 1,
      targetValue: 1,
      icon: "moon",
      displayOrder: 130,
    },
    {
      title: "Ранняя пташка",
      description: "Просмотрите урок между 5 и 8 утра",
      reward: 50,
      type: "achievement",
      category: "engagement",
      difficulty: "easy",
      requiredLevel: 1,
      targetValue: 1,
      icon: "sunrise",
      displayOrder: 131,
    },
    {
      title: "Марафонец",
      description: "Просмотрите 10 уроков в течение одного дня",
      reward: 250,
      type: "achievement",
      category: "engagement",
      difficulty: "hard",
      requiredLevel: 3,
      targetValue: 10,
      icon: "rocket",
      displayOrder: 132,
    },
    {
      title: "Первооткрыватель",
      description: "Будьте одним из первых 100 пользователей платформы",
      reward: 500,
      type: "achievement",
      category: "milestones",
      difficulty: "expert",
      requiredLevel: 1,
      targetValue: 1,
      icon: "compass",
      displayOrder: 140,
    },
    {
      title: "Щедрый друг",
      description: "Пригласите друга, который купит хотя бы один курс",
      reward: 250,
      type: "achievement",
      category: "social",
      difficulty: "medium",
      requiredLevel: 2,
      targetValue: 1,
      icon: "gift",
      displayOrder: 141,
    },
  ]);
  
  console.log("Tasks seeded successfully!");
}
